ParkingSpace.Web/Controllers/GateInController.cs
using System.Web.Mvc;
using ParkingSpace.Models;
using ParkingSpace.Services;
using System;
using ParkingSpace.Web.Printing;

namespace ParkingSpace.Web.Controllers {

  [RoutePrefix("gate-in")]
  public class GateInController : Controller {
    private App app;
    private readonly IParkingTicketPrinter printer;

    public GateInController()  {
      // this.printer = new PDFParkingTicketPrinter(this.ControllerContext);
      this.printer = new PDFParkingTicketPrinter();
      app = new App();
    }
    public GateInController(IParkingTicketPrinter printer, App app) {
      this.printer = printer;
      this.app = app;
    }

    // GET: GateIn
    [Route]
    public ActionResult Index() {
      ViewBag.GateID = app.Setting.Current.GateID;
      return View();
    }

    [HttpPost]
    [Route("CreateTicket")]
    public ActionResult CreateTicket(string plateno) {
      
      var ticket = app.ParkingTickets.CreateParkingTicket(plateno);
    
      this.printer.Print(ticket,  this.ControllerContext);

      TempData["NewTicket"] = ticket;

      
      return RedirectToAction("Index");
    }

    public ActionResult OpenBarrier() {
      throw new NotImplementedException();
    }

    private void printParkingTicket(ParkingTicket t) {
      
    }

   
  }
}

ParkingSpace.Web/Views/GateIn/Index.cshtml
@using ParkingSpace.Models;
@{
  ViewBag.Title = "Index";
  var t = (ParkingTicket)TempData["NewTicket"];
}

<h2>Gate In</h2>
<div class="well well-sm">
  @ViewBag.GateID
</div> 

@using (Html.BeginForm("CreateTicket", "GateIn")) {
  <div>
    Plate No.:<br />
    @Html.TextBox("plateNo")<br />

    <br />
    <button type="submit" class="btn btn-success">
      Issue Parking Ticket
    </button>
  </div>
}

@if (t != null) {
  <br />
  <div class="well">
    @t.ID <br />
    @t.PlateNo <br />
    @t.DateIn
  </div>
}

ParkingSpace.Web/Views/GateIn/RPT_01_PakingTicket_In.cshtml
@using ParkingSpace.Models
@model ParkingTicket


<h2>Parking ID: @Model.ID</h2>
<h3>Plate No: @Model.PlateNo</h3>
<h3>Date In: @Model.DateIn.ToString("dd/MM/yyyy HH:mm TT")</h3>
